### ISSUE TITLE
Can't get a featured front matter image to work in my app...

### ISSUE THREAD

**Issue by rchrdnsh** [ChristopherBiscardi/gatsby-mdx#260]
Having an issue trying to use a header image in the frontmatter of an mdx file.

Here is the frontmatter, with the image at the bottom. I tried putting the `./` in front of it and using parens as well, but none of those seemed to work. Am I missing something here?

```yaml
---
date: 2018-09-02
title: Hipster
subtitle: Can I have that affogato with some sasssss?
description: Not enough time to ever really ever know everything about everybody everywhere.
image: pic-1.jpg
---
```

and I query it in my component, like so:

```js
export const query = graphql`
  query GetMdxTemplate($slug: String!) {
    mdx(fields: { slug: { eq: $slug }}) {
      frontmatter {
        title
        subtitle
        date(formatString: "MMMM Do, YYYY")
        image {
          childImageSharp {
            fluid(maxWidth: 1920) {
            ...GatsbyImageSharpFluid
          }
        }
      }
      tableOfContents
      code {
        scope
        body
      }
    }
  }
`
```

and then use it my template like so:

```js
<Heading>
  <h1>{frontmatter.title}</h1>
  <h2>{frontmatter.subtitle}</h2>
  <h3>{frontmatter.date}</h3>
  <img src={frontmatter.image} alt="cool stuff." />
</Heading>
```

and get the following breaking error:

```bash
 Syntax Error: Expected Name, found <EOF>
    at getGraphQLTag (/Users/rchrdnsh/Dropbox/Code/Gatsby/rykr-app/node_modules/babel-plugin-remove-graphql-queries/index.js:107:11)
```

soooooooo...dunno what to do for this image to work...
